### ISSUE TITLE
[BUG] Fehlermeldung beim Bewegen von Tokens

### ISSUE THREAD

**Issue by vt-tom** [BlackStripedOne/fvtt-gm-token-tools#5]
**Describe the bug**
Wenn ich einen Token bewege, kommt es in der Console zu einer Fehlermeldung.
Da ich die 4.3 Beta teste, kannst du den Fehler vermutlich auch erst analysieren wenn das Update draußen ist. Es sei denn du findest den schon in 4.2.

**Versions:**
- Gamemaster Token Tools for DSA5: 0.1.4
- System: DSA 4.3.X (Beta Test)
- Foundry VTT: 10.291

**Comment by vt-tom** [comment]
![grafik](https://user-images.githubusercontent.com/80099175/223727647-f936b2ec-3434-4f0a-92e8-d3c94ea100c1.png)

**Comment by BlackStripedOne** [comment]
Hi. Danke für das Feedback. Der Fehler taucht bereits bei einer bestimmten Konstellation von DSA Modulen auf. Ein Fix ist in der Pipeline und in der nächsten Version behoben.

**Comment by JonasTrampe** [comment]
Gibt es dafür einen Branch, den ich zur Not selbst deployen könnte? Würde gerne demnächst mit einer Runde anfangen und das Plugin beißt sich leider mit dem Levels Plugin.

**Comment by BlackStripedOne** [comment]
Der Bug-Fix wird in der kommenden Version, welche für Foundry 11 und DSA 5 vorbereitet und kompatibel sein wird mit eingebaut sein. Aktuell ist dieser im `main` Branch bereits 'gefixt', so dass ein einfaches Herunterladen der Datei [gm-token-tools.min.js](https://github.com/BlackStripedOne/fvtt-gm-token-tools/blob/main/scripts/gm-token-tools.min.js) und lokales überschreiben im Modul-Ordner ausreicht.

Unabhängig davon ist der 'Bug' nicht kritisch oder Funktionseinschränkend. Es wird lediglich ein Fehler in der console geworfen. Daher beisst sich dieses Modul auch nicht mit dem Levels Modul. Beide Module sind uneingeschränkt nutzbar.

**Comment by JonasTrampe** [comment]
Ok das mache ich gleich mal.
Und leider beißt sich das doch mit dem Level Modul und vermutlich dem drag-ruler.
Denn dann löst die Treppe nicht aus und man kann keine andere Etage betreten.

**Comment by BlackStripedOne** [comment]
Bitte teile genaue Angaben zu der Aussage "leider beißt sich das doch mit dem Level Modul und vermutlich dem drag-ruler". Welcher Versionen, Foundry, Module usw und was genau die Fehlermeldung / Ursachen sind.

In verschiedenen getesteten Verssionen bei mehreren Leuten und Installationen gab es keine Kompatibilitätsprobleme zwischen diesem Modul und dem Levels (2.8.9.1 bis 3.7.5) Drag-Ruler (1.12.8 bis 1.13.3, DSA integration 1.10.3) bei Foundry (9.269 bis 10.291) und DSA (3.3.2 bis 4.2.11)

Öffne bitte in dem Fall ein neues Ticket mit einer gutem Beschreibung, so dass ich den Fehler nachstellen kann. Aktuell kann ich keine beschriebene Inkompatibilität "...löst die Treppe nicht aus und man kann keine andere Etage betreten." feststellen.
