### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Dicio83** [BlackStripedOne/fvtt-gm-token-tools#8]
Ich habe seit neustem eine Fehlermeldung wenn ich einen Token bewege.

![image](https://github.com/BlackStripedOne/fvtt-gm-token-tools/assets/116867654/c9ec9fe1-4b19-4df3-afc1-e5344ead1b60)

**Versions:**
- Gamemaster Token Tools for DSA5: [e.g. 0 1.4]
- System: dsa5 5.1.5]
- Foundry VTT: [11.311]
- Browser: ./. GM Host

**Comment by BlackStripedOne** [comment]
This is a duplicate of #5 . See description there please.
